import type { Metadata } from 'next'
import { Inter, Ubuntu } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const ubuntu = Ubuntu({ weight: ['400', '500', '700'], subsets: ['latin'], variable: '--font-ubuntu' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        <main className='p-6 md:p-12 bg-magnolia flex items-center justify-center min-h-screen'>
          <div className='max-w-7xl bg-white w-full p-4 rounded-2xl md:h-[680px]'>
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
